### PR TITLE
feat: supported Llama 3 8B and Llama 3 70B models

### LINKED ISSUE #93: Support Llama 3 8B Instruct and Llama 3 70B Instruct

### PR DESCRIPTION
**Pull request by adubovik**
Resolves #93

### CODE REVIEW

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-102.nightly-test.deltixhub.io
>E2E tests status: success

**Review by Oleksii-Klimov — APPROVED** [review]

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-102.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-102.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-102.nightly-test.deltixhub.io
>E2E tests status: failed

**Pull request merged**
