### PR TITLE
fix: allow system message with function usage

### PR DESCRIPTION
**Pull request by roman-romanov-o**
Fix this error 
```
File "/app/aidial_adapter_bedrock/llm/model/claude/v3/tools.py", line 99, in process_with_tools 
raise ValueError(f"Unknown message type {type(message)}")
ValueError: Unknown message type <class 'aidial_adapter_bedrock.llm.message.SystemMessage'>
```

### CODE REVIEW

**Comment by roman-romanov-o** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-163.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by roman-romanov-o** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-163.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by roman-romanov-o** [comment]
/deploy-review


>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-163.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by adubovik — APPROVED** [review]

**Comment by roman-romanov-o** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-163.nightly-test.deltixhub.io
>E2E tests status: failed

**Pull request merged**
