### PR TITLE
feat: supported Claude 3 Haiku

### LINKED ISSUE #86: Test support of Haiku model.

### PR DESCRIPTION
**Pull request by adubovik**
Resolves https://github.com/epam/ai-dial-adapter-bedrock/issues/86

### CODE REVIEW

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-84.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-84.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-bedrock-pr-84.nightly-test.deltixhub.io
>E2E tests status: success

**Review by vladisavvv — APPROVED** [review]

**Comment by adubovik** [comment]
Resolved https://github.com/epam/ai-dial-adapter-bedrock/issues/86

**Pull request merged**
